name: Build Pebble App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/pebble -w /pebble rebble/pebble-sdk:latest pebble build
          sudo chown -R $USER build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rotating-lines-face-pbw
          path: build/*.pbw
          if-no-files-found: error
